// backend/config/permissions.config.js
// Permission constants - NO hardcoding

import { ROLES } from './roles.config.js';

// Permission definitions
export const PERMISSIONS = {
  // Dashboard
  DASHBOARD_VIEW_ALL: 'dashboard.view.all',
  DASHBOARD_VIEW_OWN: 'dashboard.view.own',
  
  // Customers
  CUSTOMERS_VIEW_ALL: 'customers.view.all',
  CUSTOMERS_MANAGE_OWN: 'customers.manage.own',
  CUSTOMERS_VIEW_ONLY: 'customers.view.only',
  
  // Orders
  ORDERS_VIEW_ALL: 'orders.view.all',
  ORDERS_MANAGE_OWN: 'orders.manage.own',
  ORDERS_VIEW_ONLY: 'orders.view.only',
  
  // Products
  PRODUCTS_VIEW_ALL: 'products.view.all',
  PRODUCTS_MANAGE_OWN: 'products.manage.own',
  PRODUCTS_VIEW_ONLY: 'products.view.only',
  
  // Campaigns
  CAMPAIGNS_ALL: 'campaigns.all',
  CAMPAIGNS_CREATE_EDIT: 'campaigns.create.edit',
  CAMPAIGNS_CREATE_CONDITIONAL: 'campaigns.create.conditional',
  CAMPAIGNS_VIEW: 'campaigns.view',
  
  // Journeys
  JOURNEYS_ALL: 'journeys.all',
  JOURNEYS_CREATE_EDIT: 'journeys.create.edit',
  JOURNEYS_VIEW_ONLY: 'journeys.view.only',
  
  // Segments
  SEGMENTS_ALL: 'segments.all',
  SEGMENTS_CREATE_EDIT: 'segments.create.edit',
  SEGMENTS_VIEW_ONLY: 'segments.view.only',
  
  // Abandoned Carts
  ABANDONED_CARTS_ALL: 'abandoned_carts.all',
  ABANDONED_CARTS_VIEW_RECOVER: 'abandoned_carts.view.recover',
  ABANDONED_CARTS_VIEW_ONLY: 'abandoned_carts.view.only',
  
  // Store Settings
  STORE_SETTINGS_ALL: 'store_settings.all',
  STORE_SETTINGS_OWN: 'store_settings.own',
  
  // Team Management
  TEAM_MANAGE_ALL: 'team.manage.all',
  TEAM_MANAGE_OWN: 'team.manage.own',
  TEAM_INVITE: 'team.invite',
  TEAM_REMOVE: 'team.remove',
  TEAM_EDIT_ROLE: 'team.edit.role',
  TEAM_EDIT_PERMISSIONS: 'team.edit.permissions',
  TEAM_VIEW: 'team.view',
  
  // Admin Panel
  ADMIN_PANEL_ACCESS: 'admin.panel.access',
  ADMIN_IMPERSONATE: 'admin.impersonate',
  
  // Analytics
  ANALYTICS_VIEW: 'analytics.view',
  
  // Activity Logs
  ACTIVITY_LOGS_VIEW: 'activity_logs.view',
  
  // Billing
  BILLING_ALL: 'billing.all',
  BILLING_OWN: 'billing.own',
  
  // Shopify OAuth
  SHOPIFY_OAUTH_MANAGE: 'shopify.oauth.manage',
  SHOPIFY_OAUTH_OWN: 'shopify.oauth.own',

  // Email Marketing
  EMAIL_CAMPAIGNS_ALL: 'email_campaigns.all',
  EMAIL_CAMPAIGNS_CREATE_EDIT: 'email_campaigns.create.edit',
  EMAIL_CAMPAIGNS_VIEW: 'email_campaigns.view',
  EMAIL_TEMPLATES_ALL: 'email_templates.all',
  EMAIL_TEMPLATES_VIEW: 'email_templates.view',
  EMAIL_SUBSCRIBERS_ALL: 'email_subscribers.all',
  EMAIL_SUBSCRIBERS_VIEW: 'email_subscribers.view',
  EMAIL_DOMAINS_MANAGE: 'email_domains.manage',
  EMAIL_ANALYTICS_VIEW: 'email_analytics.view',
};

// Role to permissions mapping
export const ROLE_PERMISSIONS = {
  [ROLES.SUPER_ADMIN]: [
    PERMISSIONS.DASHBOARD_VIEW_ALL,
    PERMISSIONS.CUSTOMERS_VIEW_ALL,
    PERMISSIONS.ORDERS_VIEW_ALL,
    PERMISSIONS.PRODUCTS_VIEW_ALL,
    PERMISSIONS.CAMPAIGNS_ALL,
    PERMISSIONS.JOURNEYS_ALL,
    PERMISSIONS.SEGMENTS_ALL,
    PERMISSIONS.ABANDONED_CARTS_ALL,
    PERMISSIONS.STORE_SETTINGS_ALL,
    PERMISSIONS.TEAM_MANAGE_ALL,
    PERMISSIONS.TEAM_INVITE,
    PERMISSIONS.TEAM_REMOVE,
    PERMISSIONS.TEAM_EDIT_ROLE,
    PERMISSIONS.TEAM_EDIT_PERMISSIONS,
    PERMISSIONS.TEAM_VIEW,
    PERMISSIONS.BILLING_ALL,
    PERMISSIONS.SHOPIFY_OAUTH_MANAGE,
    PERMISSIONS.ADMIN_PANEL_ACCESS,
    PERMISSIONS.ADMIN_IMPERSONATE,
    PERMISSIONS.ANALYTICS_VIEW,
    PERMISSIONS.ACTIVITY_LOGS_VIEW,
    PERMISSIONS.EMAIL_CAMPAIGNS_ALL,
    PERMISSIONS.EMAIL_TEMPLATES_ALL,
    PERMISSIONS.EMAIL_SUBSCRIBERS_ALL,
    PERMISSIONS.EMAIL_DOMAINS_MANAGE,
    PERMISSIONS.EMAIL_ANALYTICS_VIEW,
  ],

  [ROLES.ADMIN]: [
    PERMISSIONS.DASHBOARD_VIEW_ALL,
    PERMISSIONS.CUSTOMERS_VIEW_ALL,
    PERMISSIONS.ORDERS_VIEW_ALL,
    PERMISSIONS.PRODUCTS_VIEW_ALL,
    PERMISSIONS.CAMPAIGNS_ALL,
    PERMISSIONS.JOURNEYS_ALL,
    PERMISSIONS.SEGMENTS_ALL,
    PERMISSIONS.ABANDONED_CARTS_ALL,
    PERMISSIONS.STORE_SETTINGS_ALL,
    PERMISSIONS.TEAM_MANAGE_ALL,
    PERMISSIONS.BILLING_ALL,
    PERMISSIONS.SHOPIFY_OAUTH_MANAGE,
    PERMISSIONS.ADMIN_PANEL_ACCESS,
    PERMISSIONS.EMAIL_CAMPAIGNS_ALL,
    PERMISSIONS.EMAIL_TEMPLATES_ALL,
    PERMISSIONS.EMAIL_SUBSCRIBERS_ALL,
    PERMISSIONS.EMAIL_DOMAINS_MANAGE,
    PERMISSIONS.EMAIL_ANALYTICS_VIEW,
  ],

  [ROLES.STORE_OWNER]: [
    PERMISSIONS.DASHBOARD_VIEW_OWN,
    PERMISSIONS.CUSTOMERS_MANAGE_OWN,
    PERMISSIONS.ORDERS_MANAGE_OWN,
    PERMISSIONS.PRODUCTS_MANAGE_OWN,
    PERMISSIONS.CAMPAIGNS_CREATE_EDIT,
    PERMISSIONS.JOURNEYS_CREATE_EDIT,
    PERMISSIONS.SEGMENTS_CREATE_EDIT,
    PERMISSIONS.ABANDONED_CARTS_VIEW_RECOVER,
    PERMISSIONS.STORE_SETTINGS_OWN,
    PERMISSIONS.TEAM_MANAGE_OWN,
    PERMISSIONS.TEAM_INVITE,
    PERMISSIONS.TEAM_REMOVE,
    PERMISSIONS.TEAM_EDIT_ROLE,
    PERMISSIONS.TEAM_EDIT_PERMISSIONS,
    PERMISSIONS.TEAM_VIEW,
    PERMISSIONS.BILLING_OWN,
    PERMISSIONS.SHOPIFY_OAUTH_OWN,
    PERMISSIONS.ANALYTICS_VIEW,
    PERMISSIONS.ACTIVITY_LOGS_VIEW,
    PERMISSIONS.EMAIL_CAMPAIGNS_CREATE_EDIT,
    PERMISSIONS.EMAIL_TEMPLATES_ALL,
    PERMISSIONS.EMAIL_SUBSCRIBERS_ALL,
    PERMISSIONS.EMAIL_DOMAINS_MANAGE,
    PERMISSIONS.EMAIL_ANALYTICS_VIEW,
  ],

  [ROLES.MANAGER]: [
    PERMISSIONS.DASHBOARD_VIEW_OWN,
    PERMISSIONS.CUSTOMERS_MANAGE_OWN,
    PERMISSIONS.ORDERS_VIEW_ONLY,
    PERMISSIONS.PRODUCTS_MANAGE_OWN,
    PERMISSIONS.CAMPAIGNS_CREATE_EDIT,
    PERMISSIONS.JOURNEYS_CREATE_EDIT,
    PERMISSIONS.SEGMENTS_CREATE_EDIT,
    PERMISSIONS.ABANDONED_CARTS_VIEW_RECOVER,
    PERMISSIONS.TEAM_INVITE, // Can only invite team_member and viewer
    PERMISSIONS.TEAM_VIEW,
    PERMISSIONS.ANALYTICS_VIEW,
    PERMISSIONS.EMAIL_CAMPAIGNS_CREATE_EDIT,
    PERMISSIONS.EMAIL_TEMPLATES_ALL,
    PERMISSIONS.EMAIL_SUBSCRIBERS_VIEW,
    PERMISSIONS.EMAIL_ANALYTICS_VIEW,
  ],

  [ROLES.TEAM_MEMBER]: [
    PERMISSIONS.DASHBOARD_VIEW_OWN,
    PERMISSIONS.CUSTOMERS_VIEW_ONLY,
    PERMISSIONS.ORDERS_VIEW_ONLY,
    PERMISSIONS.PRODUCTS_VIEW_ONLY,
    PERMISSIONS.CAMPAIGNS_VIEW,
    PERMISSIONS.JOURNEYS_VIEW_ONLY,
    PERMISSIONS.SEGMENTS_VIEW_ONLY,
    PERMISSIONS.ABANDONED_CARTS_VIEW_ONLY,
    PERMISSIONS.EMAIL_CAMPAIGNS_VIEW,
    PERMISSIONS.EMAIL_TEMPLATES_VIEW,
    PERMISSIONS.EMAIL_ANALYTICS_VIEW,
  ],

  [ROLES.VIEWER]: [
    PERMISSIONS.DASHBOARD_VIEW_OWN,
    PERMISSIONS.ANALYTICS_VIEW,
    PERMISSIONS.CAMPAIGNS_VIEW,
  ],
  
  [ROLES.USER]: [
    PERMISSIONS.DASHBOARD_VIEW_OWN,
    PERMISSIONS.CUSTOMERS_VIEW_ONLY,
    PERMISSIONS.ORDERS_VIEW_ONLY,
    PERMISSIONS.PRODUCTS_VIEW_ONLY,
    PERMISSIONS.CAMPAIGNS_VIEW,
    PERMISSIONS.CAMPAIGNS_CREATE_CONDITIONAL,
    PERMISSIONS.JOURNEYS_VIEW_ONLY,
    PERMISSIONS.SEGMENTS_VIEW_ONLY,
    PERMISSIONS.ABANDONED_CARTS_VIEW_ONLY,
  ],
};

/**
 * Get all permissions for a role
 * @param {string} role - User role
 * @returns {string[]}
 */
export function getPermissionsForRole(role) {
  return ROLE_PERMISSIONS[role] || [];
}

/**
 * Check if a permission exists
 * @param {string} permission - Permission to check
 * @returns {boolean}
 */
export function isValidPermission(permission) {
  return Object.values(PERMISSIONS).includes(permission);
}

