import { NextRequest, NextResponse } from 'next/server';

import { listJourneyVersionMetadata, saveJourneyVersion } from '@/lib/journey-engine/versioning';
import type { JourneyDefinition } from '@/lib/types/journey';
import { readJsonFile } from '@/lib/utils/json-storage';

export const runtime = 'nodejs';

interface VersionRequestPayload {
  label?: string;
  reason?: string;
  summary?: string;
  createdBy?: string;
  autoGenerated?: boolean;
}



const getErrorMessage = (error: unknown): string => (error instanceof Error ? error.message : String(error));

const normaliseLabel = (payload: VersionRequestPayload, journeyName: string): string => {
  if (payload.label && payload.label.trim()) return payload.label.trim();
  if (payload.reason && payload.reason.trim()) return payload.reason.trim();
  return `${journeyName || 'Journey'} snapshot`;
};

const normaliseBoolean = (value: unknown): boolean | undefined =>
  typeof value === 'boolean' ? value : undefined;

export async function GET(
  _request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const resolved = await params;
    const versions = listJourneyVersionMetadata(resolved.id);
    return NextResponse.json({ versions });
  } catch (error) {
    return NextResponse.json({ error: getErrorMessage(error) || 'Failed to load versions' }, { status: 500 });
  }
}

export async function POST(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const resolved = await params;
    const body = (await request.json().catch(() => ({}))) as VersionRequestPayload;

    const journeys = readJsonFile<JourneyDefinition>('journeys.json');
    const journey = journeys.find(item => item.id === resolved.id);
    if (!journey) {
      return NextResponse.json({ error: 'Journey not found' }, { status: 404 });
    }

    const label = normaliseLabel(body, journey.name ?? 'Journey');

    const summary =
      typeof body.summary === 'string' && body.summary.trim().length > 0 ? body.summary.trim() : undefined;
    const createdBy =
      typeof body.createdBy === 'string' && body.createdBy.trim().length > 0 ? body.createdBy.trim() : undefined;
    const explicitAutoGenerated = normaliseBoolean(body.autoGenerated);
    const autoGenerated =
      explicitAutoGenerated ??
      (/auto snapshot/i.test(label) ||
        (typeof body.reason === 'string' && /auto/i.test(body.reason)));

    const version = saveJourneyVersion(journey, {
      label,
      summary,
      createdBy,
      autoGenerated,
    });

    return NextResponse.json({ version });
  } catch (error) {
    return NextResponse.json({ error: getErrorMessage(error) || 'Failed to create version' }, { status: 500 });
  }
}

