import type { JourneyDefinition } from './journey';

export interface JourneyVersion {
  id: string;
  journeyId: string;
  label: string;
  summary?: string;
  createdAt: number;
  createdBy?: string;
  autoGenerated?: boolean;
  snapshot: JourneyDefinition;
}

export interface JourneyVersionMetadata extends Omit<JourneyVersion, 'snapshot'> {
  stats: {
    nodeCount: number;
    edgeCount: number;
    status: JourneyDefinition['status'];
  };
}

