export const dynamic = 'force-dynamic';
import { NextRequest, NextResponse } from 'next/server';

import { saveJourneyVersion } from '@/lib/journey-engine/versioning';
import type { JourneyConfig, JourneyDefinition, JourneyStats } from '@/lib/types/journey';
import { getJourneyById, updateJourney, deleteJourney } from '@/lib/journey-engine/storage';

export const runtime = 'nodejs';

const defaultConfig: JourneyConfig = {
  reEntryRules: {
    allow: false,
    cooldownDays: 0,
  },
  maxEnrollments: null,
  timezone: 'UTC',
};

const defaultStats: JourneyStats = {
  totalEnrollments: 0,
  activeEnrollments: 0,
  completedEnrollments: 0,
  goalConversionRate: 0,
};

function withJourneyDefaults(journey: JourneyDefinition): JourneyDefinition {
  const config: JourneyConfig = {
    ...defaultConfig,
    ...(journey.config || {}),
    reEntryRules: {
      ...defaultConfig.reEntryRules,
      ...(journey.config?.reEntryRules || {}),
    },
  };

  if (config.maxEnrollments !== null) {
    const numeric = Number(config.maxEnrollments);
    config.maxEnrollments = Number.isFinite(numeric) ? numeric : null;
  }

  const stats: JourneyStats = {
    ...defaultStats,
    ...(journey.stats || {}),
  };

  const createdAt = journey.createdAt ?? new Date().toISOString();
  const updatedAt = journey.updatedAt ?? createdAt;

  return {
    ...journey,
    createdAt,
    updatedAt,
    config,
    stats,
  };
}

const getErrorMessage = (error: unknown): string => (error instanceof Error ? error.message : String(error));

const normaliseNodes = (nodes: unknown): JourneyDefinition['nodes'] =>
  Array.isArray(nodes) ? (nodes as JourneyDefinition['nodes']) : [];

const normaliseEdges = (edges: unknown): JourneyDefinition['edges'] =>
  Array.isArray(edges) ? (edges as JourneyDefinition['edges']) : [];

export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const resolved = await params;
    const journey = await getJourneyById(resolved.id);
    if (!journey) return NextResponse.json({ error: 'Not found' }, { status: 404 });
    return NextResponse.json({ journey: withJourneyDefaults(journey) });
  } catch (error) {
    console.error('[journeys][GET]', error);
    return NextResponse.json({ error: getErrorMessage(error) }, { status: 500 });
  }
}

export async function PUT(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const resolved = await params;
    const updates = (await request.json()) as Partial<JourneyDefinition>;
    const existing = await getJourneyById(resolved.id);
    if (!existing) return NextResponse.json({ error: 'Not found' }, { status: 404 });

    saveJourneyVersion(existing, {
      label: `${existing.name || 'Journey'} (auto save)` ,
      summary: 'Snapshot before update',
      autoGenerated: true,
    });

    const updated: JourneyDefinition = {
      ...existing,
      ...updates,
      updatedAt: new Date().toISOString(),
      nodes: updates.nodes ? normaliseNodes(updates.nodes) : existing.nodes,
      edges: updates.edges ? normaliseEdges(updates.edges) : existing.edges,
    };
    const finalJourney = withJourneyDefaults(updated);
    await updateJourney(finalJourney);
    return NextResponse.json({ journey: finalJourney });
  } catch (error) {
    console.error('[journeys][PUT]', error);
    return NextResponse.json({ error: getErrorMessage(error) }, { status: 500 });
  }
}

export async function DELETE(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const resolved = await params;
    const existing = await getJourneyById(resolved.id);
    if (!existing) return NextResponse.json({ error: 'Not found' }, { status: 404 });
    await deleteJourney(resolved.id);
    return NextResponse.json({ success: true });
  } catch (error) {
    console.error('[journeys][DELETE]', error);
    return NextResponse.json({ error: getErrorMessage(error) }, { status: 500 });
  }
}


