"use client";

import { formatDistanceToNow } from 'date-fns';
import { Activity, Clock, GitCompare, Sparkles } from 'lucide-react';

import { Button } from '@/components/ui/button';
import { cn } from '@/lib/utils';
import type { JourneyVersionMetadata } from '@/lib/types/journey-version';

interface VersionHistoryListProps {
  versions: JourneyVersionMetadata[];
  onCreateSnapshot?: () => void;
  onPreview?: (versionId: string) => void;
  onCompare?: (versionId: string) => void;
  onRestore?: (versionId: string) => void;
  currentVersionId?: string;
  isCreatingSnapshot?: boolean;
  restoringVersionId?: string | null;
}

export function VersionHistoryList({
  versions,
  onCreateSnapshot,
  onPreview,
  onCompare,
  onRestore,
  currentVersionId,
  isCreatingSnapshot = false,
  restoringVersionId = null,
}: VersionHistoryListProps) {
  return (
    <div className="space-y-6">
      <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
        <div>
          <h1 className="text-2xl font-semibold text-[#3A3028]">Version History</h1>
          <p className="text-sm text-[#8B7F76]">
            Snapshots captured across key edits. Restore instantly or compare differences before activating a journey.
          </p>
        </div>
        {onCreateSnapshot ? (
          <Button
            onClick={onCreateSnapshot}
            disabled={isCreatingSnapshot}
            className="bg-[#D4A574] text-white hover:bg-[#C18E5D]"
          >
            {isCreatingSnapshot ? 'Creating…' : 'Create Snapshot'}
          </Button>
        ) : null}
      </div>

      <div className="relative border-l border-dashed border-[#E8E4DE] pl-6">
        {versions.length === 0 ? (
          <div className="rounded-2xl border border-dashed border-[#E8E4DE] bg-white/80 px-6 py-8 text-sm text-[#8B7F76]">
            No versions yet. Create a snapshot to start tracking changes.
          </div>
        ) : (
          versions.map((version, index) => {
            const isCurrent = version.id === currentVersionId;
            return (
              <div key={version.id} className="relative mb-6 last:mb-0">
                <span
                  className={cn(
                    'absolute -left-[14px] top-2 flex h-6 w-6 items-center justify-center rounded-full border-2 bg-white text-[11px] font-semibold',
                    isCurrent ? 'border-[#2F7A3E] text-[#2F7A3E]' : 'border-[#D4A574] text-[#B8875C]'
                  )}
                >
                  {versions.length - index}
                </span>
                <div className="rounded-2xl border border-[#E8E4DE] bg-white/90 p-5 shadow-sm transition hover:-translate-y-0.5 hover:shadow-md">
                  <div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between">
                    <div className="space-y-2">
                      <div className="flex items-center gap-2">
                        <h2 className="text-lg font-semibold text-[#4A4139]">
                          {isCurrent ? 'Current Version' : version.label}
                        </h2>
                        {version.autoGenerated ? (
                          <span className="flex items-center gap-1 rounded-full bg-[#F6F1EB] px-2 py-1 text-[10px] font-semibold uppercase tracking-[0.2em] text-[#B8875C]">
                            <Sparkles className="h-3 w-3" /> Auto
                          </span>
                        ) : null}
                      </div>
                      {version.summary ? <p className="text-sm text-[#8B7F76]">{version.summary}</p> : null}
                      <p className="flex flex-wrap items-center gap-2 text-xs uppercase tracking-wide text-[#B9AA9F]">
                        <Clock className="h-3.5 w-3.5" />
                        {formatDistanceToNow(version.createdAt, { addSuffix: true })}
                        {version.stats.status ? (
                          <>
                            <span className="mx-1">•</span>
                            {version.stats.status}
                          </>
                        ) : null}
                        <span className="mx-1">•</span>
                        {version.stats.nodeCount} nodes / {version.stats.edgeCount} edges
                      </p>
                      {version.createdBy ? (
                        <p className="text-xs text-[#8B7F76]">Captured by {version.createdBy}</p>
                      ) : null}
                    </div>
                    <div className="flex flex-wrap items-center gap-2">
                      {onPreview ? (
                        <Button
                          variant="outline"
                          size="sm"
                          onClick={() => onPreview(version.id)}
                          className="border-[#E8E4DE] bg-white text-[#4A4139] hover:bg-[#F6F1EB]"
                        >
                          <Activity className="mr-1 h-4 w-4" /> View
                        </Button>
                      ) : null}
                      {onCompare ? (
                        <Button
                          variant="outline"
                          size="sm"
                          onClick={() => onCompare(version.id)}
                          className="border-[#E8E4DE] bg-white text-[#4A4139] hover:bg-[#F6F1EB]"
                        >
                          <GitCompare className="mr-1 h-4 w-4" />
                          Compare
                        </Button>
                      ) : null}
                      {onRestore && !isCurrent ? (
                        <Button
                          size="sm"
                          onClick={() => onRestore(version.id)}
                          disabled={restoringVersionId === version.id}
                          className="bg-[#B4A0D6] text-white hover:bg-[#9A86BD]"
                        >
                          {restoringVersionId === version.id ? 'Restoring…' : 'Restore'}
                        </Button>
                      ) : null}
                    </div>
                  </div>
                </div>
              </div>
            );
          })
        )}
      </div>
    </div>
  );
}

